services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local

  svelte-app:
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - db